#!/usr/bin/env python3
"""Generate complete 64 hexagram data for I Ching divination app."""
import json

# All 64 hexagrams in King Wen sequence
# Format: (number, binary, chinese, pinyin, english, upper_tri, lower_tri,
#          judgment_en, judgment_cn, image_en, image_cn, lines[6])

HEXAGRAMS = [
(1, "111111", "乾", "qián", "The Creative", "111", "111",
 "The Creative works sublime success, furthering through perseverance.",
 "乾：元，亨，利，貞。",
 "The movement of heaven is full of power. Thus the superior man makes himself strong and untiring.",
 "天行健，君子以自強不息。",
 ["Hidden dragon. Do not act.",
  "Dragon appearing in the field. It furthers one to see the great man.",
  "All day long the superior man is creatively active. At nightfall his mind is beset with cares. Danger. No blame.",
  "Wavering flight over the depths. No blame.",
  "Flying dragon in the heavens. It furthers one to see the great man.",
  "Arrogant dragon will have cause to repent."]),

(2, "000000", "坤", "kūn", "The Receptive", "000", "000",
 "The Receptive brings about sublime success, furthering through the perseverance of a mare.",
 "坤：元，亨，利牝馬之貞。",
 "The earth's condition is receptive devotion. Thus the superior man who has breadth of character carries the outer world.",
 "地勢坤，君子以厚德載物。",
 ["When there is hoarfrost underfoot, solid ice is not far off.",
  "Straight, square, great. Without purpose, yet nothing remains unfurthered.",
  "Hidden lines. One is able to remain persevering.",
  "A tied-up sack. No blame, no praise.",
  "A yellow lower garment brings supreme good fortune.",
  "Dragons fight in the meadow. Their blood is black and yellow."]),

(3, "010001", "屯", "zhūn", "Difficulty at the Beginning", "010", "001",
 "Difficulty at the Beginning works supreme success, furthering through perseverance. Nothing should be undertaken. It furthers one to appoint helpers.",
 "屯：元，亨，利，貞，勿用，有攸往，利建侯。",
 "Clouds and thunder: The image of Difficulty at the Beginning. Thus the superior man brings order out of confusion.",
 "雲，雷，屯；君子以經綸。",
 ["Hesitation and hindrance. It furthers one to remain persevering. It furthers one to appoint helpers.",
  "Difficulties pile up. The girl is chaste; she does not pledge herself.",
  "Whoever hunts deer without the forester only loses his way in the forest.",
  "Horse and wagon part. Strive for union.",
  "Difficulties in blessing. A little perseverance brings good fortune. Great perseverance brings misfortune.",
  "Horse and wagon part. Bloody tears flow."]),

(4, "100010", "蒙", "méng", "Youthful Folly", "100", "010",
 "Youthful Folly has success. It is not I who seek the young fool; the young fool seeks me. At the first oracle I inform him. If he asks two or three times, it is importunity.",
 "蒙：亨。匪我求童蒙，童蒙求我。初筮告，再三瀆，瀆則不告。利貞。",
 "A spring wells up at the foot of the mountain. Thus the superior man fosters his character by thoroughness in all that he does.",
 "山下出泉，蒙；君子以果行育德。",
 ["To make a fool develop, it furthers one to apply discipline.",
  "To bear with fools in kindliness brings good fortune. To know how to take women brings good fortune.",
  "Take not a maiden who loses herself at the sight of a man of bronze.",
  "Entangled folly brings humiliation.",
  "Childlike folly brings good fortune.",
  "In punishing folly, it does not further one to commit transgressions."]),

(5, "010111", "需", "xū", "Waiting", "010", "111",
 "Waiting. If you are sincere, you have light and success. Perseverance brings good fortune. It furthers one to cross the great water.",
 "需：有孚，光亨，貞吉。利涉大川。",
 "Clouds rise up to heaven. The image of Waiting. Thus the superior man eats and drinks, is joyous and of good cheer.",
 "雲上於天，需；君子以飲食宴樂。",
 ["Waiting in the meadow. It furthers one to abide in what endures. No blame.",
  "Waiting on the sand. There is some gossip. The end brings good fortune.",
  "Waiting in the mud brings about the arrival of the enemy.",
  "Waiting in blood. Get out of the pit.",
  "Waiting at meat and drink. Perseverance brings good fortune.",
  "One falls into the pit. Three uninvited guests arrive. Honor them, and in the end there will be good fortune."]),

(6, "111010", "訟", "sòng", "Conflict", "111", "010",
 "Conflict. You are sincere and are being obstructed. A cautious halt halfway brings good fortune. Going through to the end brings misfortune.",
 "訟：有孚，窒。惕中吉。終凶。利見大人，不利涉大川。",
 "Heaven and water go their opposite ways. Thus in all his transactions the superior man carefully considers the beginning.",
 "天與水違行，訟；君子以作事謀始。",
 ["If one does not perpetuate the affair, there is a little gossip. In the end, good fortune comes.",
  "One cannot engage in conflict. One returns home. The people of his town, three hundred households, remain free of guilt.",
  "To nourish oneself on ancient virtue induces perseverance. Danger. In the end, good fortune comes.",
  "One cannot engage in conflict. One turns back and submits to fate. Peace. Perseverance brings good fortune.",
  "To contend before him brings supreme good fortune.",
  "Even if by chance a leather belt is bestowed on one, by the end of a morning it will have been snatched away three times."]),

(7, "000010", "師", "shī", "The Army", "000", "010",
 "The Army. The army needs perseverance and a strong man. Good fortune without blame.",
 "師：貞，丈人吉，無咎。",
 "In the middle of the earth is water. Thus the superior man increases his masses by generosity toward the people.",
 "地中有水，師；君子以容民畜眾。",
 ["An army must set forth in proper order. If the order is not good, misfortune threatens.",
  "In the midst of the army. Good fortune. No blame. The king bestows a triple decoration.",
  "Perchance the army carries corpses in the wagon. Misfortune.",
  "The army retreats. No blame.",
  "There is game in the field. It furthers one to catch it. Without blame.",
  "The great prince issues commands, founds states, vests families with fiefs. Inferior people should not be employed."]),

(8, "010000", "比", "bǐ", "Holding Together", "010", "000",
 "Holding Together brings good fortune. Inquire of the oracle once again whether you possess sublimity, constancy, and perseverance; then there is no blame.",
 "比：吉。原筮元永貞，無咎。",
 "On the earth is water. Thus the kings of antiquity bestowed the different states as fiefs and cultivated friendly relations with the feudal lords.",
 "地上有水，比；先王以建萬國，親諸侯。",
 ["Hold to him in truth and loyalty; this is without blame. Truth, like a full earthen bowl.",
  "Hold to him inwardly. Perseverance brings good fortune.",
  "You hold together with the wrong people.",
  "Hold to him outwardly also. Perseverance brings good fortune.",
  "Manifestation of holding together. In the hunt the king uses beaters on three sides only. The citizens need no warning. Good fortune.",
  "He finds no head for holding together. Misfortune."]),

(9, "110111", "小畜", "xiǎo chù", "The Taming Power of the Small", "110", "111",
 "The Taming Power of the Small has success. Dense clouds, no rain from our western region.",
 "小畜：亨。密雲不雨，自我西郊。",
 "The wind drives across heaven. Thus the superior man refines the outward aspect of his nature.",
 "風行天上，小畜；君子以懿文德。",
 ["Return to the way. How could there be blame in this? Good fortune.",
  "He allows himself to be drawn into returning. Good fortune.",
  "The spokes burst out of the wagon wheels. Man and wife roll their eyes.",
  "If you are sincere, blood vanishes and fear gives way. No blame.",
  "If you are sincere and loyally attached, you are rich in your neighbor.",
  "The rain comes, there is rest. This is due to the lasting effect of character. The woman is in danger. The moon is nearly full."]),

(10, "111011", "履", "lǚ", "Treading", "111", "011",
 "Treading upon the tail of the tiger. It does not bite the man. Success.",
 "履：履虎尾，不咥人，亨。",
 "Heaven above, the lake below. Thus the superior man discriminates between high and low.",
 "上天下澤，履；君子以辯上下，定民志。",
 ["Simple conduct. Progress without blame.",
  "Treading a smooth, level course. The perseverance of a dark man brings good fortune.",
  "A one-eyed man is able to see, a lame man is able to tread. But he treads on the tail of the tiger. Misfortune.",
  "He treads on the tail of the tiger. Caution and circumspection lead ultimately to good fortune.",
  "Resolute conduct. Perseverance with awareness of danger.",
  "Look to your conduct and weigh the favorable signs. When everything is fulfilled, supreme good fortune comes."]),

(11, "000111", "泰", "tài", "Peace", "000", "111",
 "Peace. The small departs, the great approaches. Good fortune. Success.",
 "泰：小往大來，吉亨。",
 "Heaven and earth unite: Peace. Thus the ruler divides and completes the course of heaven and earth.",
 "天地交，泰；后以財成天地之道。",
 ["When ribbon grass is pulled up, the sod comes with it. Undertakings bring good fortune.",
  "Bearing with the uncultured in gentleness, fording the river with resolution. One does not neglect what is distant.",
  "No plain not followed by a slope. No going not followed by a return. He who remains persevering in danger is without blame.",
  "He flutters down, not boasting of his wealth, together with his neighbor, guileless and sincere.",
  "The sovereign I gives his daughter in marriage. This brings blessing and supreme good fortune.",
  "The wall falls back into the moat. Use no army now. Make your commands known within your own town. Perseverance brings humiliation."]),

(12, "111000", "否", "pǐ", "Standstill", "111", "000",
 "Standstill. Evil people do not further the perseverance of the superior man. The great departs; the small approaches.",
 "否：否之匪人，不利君子貞，大往小來。",
 "Heaven and earth do not unite: Standstill. Thus the superior man falls back upon his inner worth.",
 "天地不交，否；君子以儉德辟難。",
 ["When ribbon grass is pulled up, the sod comes with it. Perseverance brings good fortune and success.",
  "They bear and endure; this means good fortune for inferior people. The standstill serves to help the great man to attain success.",
  "They bear shame.",
  "He who acts at the command of the highest remains without blame. Those of like mind partake of the blessing.",
  "Standstill is giving way. Good fortune for the great man. What if it should fail? He ties it to a cluster of mulberry shoots.",
  "The standstill comes to an end. First standstill, then good fortune."]),

(13, "111101", "同人", "tóng rén", "Fellowship with Men", "111", "101",
 "Fellowship with Men in the open. Success. It furthers one to cross the great water.",
 "同人：同人于野，亨。利涉大川，利君子貞。",
 "Heaven together with fire. Thus the superior man organizes the clans and makes distinctions between things.",
 "天與火，同人；君子以類族辨物。",
 ["Fellowship with men at the gate. No blame.",
  "Fellowship with men in the clan. Humiliation.",
  "He hides weapons in the thicket; he climbs the high hill in front of it. For three years he does not rise up.",
  "He climbs up on his wall; he cannot attack. Good fortune.",
  "Men bound in fellowship first weep and lament, but afterward they laugh. Great armies can meet and join together.",
  "Fellowship with men in the meadow. No remorse."]),

(14, "101111", "大有", "dà yǒu", "Possession in Great Measure", "101", "111",
 "Possession in Great Measure. Supreme success.",
 "大有：元亨。",
 "Fire in heaven above. Thus the superior man curbs evil and furthers good.",
 "火在天上，大有；君子以遏惡揚善。",
 ["No relationship with what is harmful; there is no blame in this. If one remains conscious of difficulty, one remains without blame.",
  "A big wagon for loading. One may undertake something. No blame.",
  "A prince offers it to the Son of Heaven. A petty man cannot do this.",
  "He makes a difference between himself and his neighbor. No blame.",
  "He whose truth is accessible, yet dignified, has good fortune.",
  "He is blessed by heaven. Good fortune. Nothing that does not further."]),

(15, "000100", "謙", "qiān", "Modesty", "000", "100",
 "Modesty creates success. The superior man carries things through.",
 "謙：亨，君子有終。",
 "Within the earth, a mountain. Thus the superior man reduces that which is too much, and augments that which is too little.",
 "地中有山，謙；君子以裒多益寡。",
 ["A superior man modest about his modesty may cross the great water. Good fortune.",
  "Modesty that comes to expression. Perseverance brings good fortune.",
  "A superior man of modesty and merit carries things to conclusion. Good fortune.",
  "Nothing that would not further modesty in movement.",
  "No boasting of wealth before one's neighbor. It is favorable to attack with force. Nothing that would not further.",
  "Modesty that comes to expression. It is favorable to set armies marching to chastise one's own city and one's country."]),

(16, "001000", "豫", "yù", "Enthusiasm", "001", "000",
 "Enthusiasm. It furthers one to install helpers and to set armies marching.",
 "豫：利建侯行師。",
 "Thunder comes resounding out of the earth. Thus the ancient kings made music to honor merit.",
 "雷出地奮，豫；先王以作樂崇德。",
 ["Enthusiasm that expresses itself brings misfortune.",
  "Firm as a rock. Not a whole day. Perseverance brings good fortune.",
  "Enthusiasm that looks upward creates remorse. Hesitation brings remorse.",
  "The source of enthusiasm. He achieves great things. Doubt not. You gather friends around you as a hair clasp gathers the hair.",
  "Persistently ill, and still does not die.",
  "Deluded enthusiasm. But if after completion one changes, there is no blame."]),

(17, "011001", "隨", "suí", "Following", "011", "001",
 "Following has supreme success. Perseverance furthers. No blame.",
 "隨：元亨利貞，無咎。",
 "Thunder in the middle of the lake. Thus the superior man at nightfall goes indoors for rest and recuperation.",
 "澤中有雷，隨；君子以嚮晦入宴息。",
 ["The standard is changing. Perseverance brings good fortune. To go out of the door in company produces deeds.",
  "If one clings to the small boy, one loses the strong man.",
  "If one clings to the strong man, one loses the small boy. Through following one finds what one seeks.",
  "Following creates success. Perseverance brings misfortune. To go one's way with sincerity brings clarity. How could there be blame?",
  "Sincere in the good. Good fortune.",
  "He meets with firm allegiance and is still further bound. The king introduces him to the Western Mountain."]),

(18, "100110", "蠱", "gǔ", "Work on What Has Been Spoiled", "100", "110",
 "Work on What Has Been Spoiled has supreme success. It furthers one to cross the great water. Before the starting point, three days. After the starting point, three days.",
 "蠱：元亨，利涉大川。先甲三日，後甲三日。",
 "The wind blows low on the mountain. Thus the superior man stirs up the people and strengthens their spirit.",
 "山下有風，蠱；君子以振民育德。",
 ["Setting right what has been spoiled by the father. If there is a son, no blame rests upon the departed father.",
  "Setting right what has been spoiled by the mother. One must not be too persevering.",
  "Setting right what has been spoiled by the father. There will be a little remorse. No great blame.",
  "Tolerating what has been spoiled by the father. In continuing one sees humiliation.",
  "Setting right what has been spoiled by the father. One meets with praise.",
  "He does not serve kings and princes, sets himself higher goals."]),

(19, "000011", "臨", "lín", "Approach", "000", "011",
 "Approach has supreme success. Perseverance furthers. When the eighth month comes, there will be misfortune.",
 "臨：元，亨，利，貞。至于八月有凶。",
 "The earth above the lake. Thus the superior man is inexhaustible in his will to teach, and without limits in his tolerance.",
 "地上有澤，臨；君子以教思無窮，容保民無疆。",
 ["Joint approach. Perseverance brings good fortune.",
  "Joint approach. Good fortune. Everything furthers.",
  "Comfortable approach. Nothing that would further. If one is induced to grieve over it, one becomes free of blame.",
  "Complete approach. No blame.",
  "Wise approach. This is right for a great prince. Good fortune.",
  "Great-hearted approach. Good fortune. No blame."]),

(20, "110000", "觀", "guān", "Contemplation", "110", "000",
 "Contemplation. The ablution has been made, but not yet the offering. Full of trust they look up to him.",
 "觀：盥而不薦，有孚顒若。",
 "The wind blows over the earth. Thus the kings of old visited the regions of the world, contemplated the people, and gave them instruction.",
 "風行地上，觀；先王以省方觀民設教。",
 ["Boy-like contemplation. For an inferior man, no blame. For a superior man, humiliation.",
  "Contemplation through the crack of the door. Furthering for the perseverance of a woman.",
  "Contemplation of my life decides the choice between advance and retreat.",
  "Contemplation of the light of the kingdom. It furthers one to exert influence as the guest of a king.",
  "Contemplation of my life. The superior man is without blame.",
  "Contemplation of his life. The superior man is without blame."]),

(21, "101001", "噬嗑", "shì kè", "Biting Through", "101", "001",
 "Biting Through has success. It is favorable to let justice be administered.",
 "噬嗑：亨。利用獄。",
 "Thunder and lightning: Biting Through. Thus the kings of former times made firm the laws through clearly defined penalties.",
 "雷電，噬嗑；先王以明罰敕法。",
 ["His feet are fastened in the stocks, so that his toes disappear. No blame.",
  "Bites through tender meat, so that his nose disappears. No blame.",
  "Bites on old dried meat and strikes on something poisonous. Slight humiliation. No blame.",
  "Bites on dried gristly meat. Receives metal arrows. It furthers one to be mindful of difficulties and to be persevering. Good fortune.",
  "Bites on dried lean meat. Receives yellow gold. Perseveringly aware of danger. No blame.",
  "His neck is fastened in the wooden cangue, so that his ears disappear. Misfortune."]),

(22, "100101", "賁", "bì", "Grace", "100", "101",
 "Grace has success. In small matters it is favorable to undertake something.",
 "賁：亨。小利有攸往。",
 "Fire at the foot of the mountain. Thus the superior man proceeds to clear up current affairs. But he dare not decide controversial issues in this way.",
 "山下有火，賁；君子以明庶政，無敢折獄。",
 ["He lends grace to his toes, leaves the carriage, and walks.",
  "Lends grace to the beard on his chin.",
  "Graceful and moist. Constant perseverance brings good fortune.",
  "Grace or simplicity? A white horse comes as if on wings. He is not a robber; he will woo at the right time.",
  "Grace in hills and gardens. The roll of silk is meager and small. Humiliation, but in the end good fortune.",
  "Simple grace. No blame."]),

(23, "100000", "剝", "bō", "Splitting Apart", "100", "000",
 "Splitting Apart. It does not further one to go anywhere.",
 "剝：不利有攸往。",
 "The mountain rests on the earth. Thus those above can ensure their position only by giving generously to those below.",
 "山附於地，剝；上以厚下安宅。",
 ["The leg of the bed is split. Those who persevere are destroyed. Misfortune.",
  "The bed is split at the edge. Those who persevere are destroyed. Misfortune.",
  "He splits with them. No blame.",
  "The bed is split up to the skin. Misfortune.",
  "A shoal of fishes. Favor comes through the court ladies. Everything acts to further.",
  "There is a large fruit still uneaten. The superior man receives a carriage. The house of the inferior man is split apart."]),

(24, "000001", "復", "fù", "Return", "000", "001",
 "Return. Success. Going out and coming in without error. Friends come without blame. To and fro goes the way. On the seventh day comes return.",
 "復：亨。出入無疾，朋來無咎。反復其道，七日來復，利有攸往。",
 "Thunder within the earth. Thus the kings of old closed the passes at the time of solstice.",
 "雷在地中，復；先王以至日閉關。",
 ["Return from a short distance. No need for remorse. Great good fortune.",
  "Quiet return. Good fortune.",
  "Repeated return. Danger. No blame.",
  "Walking in the midst of others, one returns alone.",
  "Noble-hearted return. No remorse.",
  "Missing the return. Misfortune. If armies are set marching in this way, one will suffer a great defeat."]),

(25, "111001", "無妄", "wú wàng", "Innocence", "111", "001",
 "Innocence. Supreme success. Perseverance furthers. If someone is not as he should be, he has misfortune.",
 "無妄：元，亨，利，貞。其匪正有眚，不利有攸往。",
 "Under heaven, thunder rolls. Thus the kings of old, rich in virtue and in harmony with the time, fostered and nourished all beings.",
 "天下雷行，物與無妄；先王以茂對時育萬物。",
 ["Innocent behavior brings good fortune.",
  "If one does not count on the harvest while plowing, then it furthers one to undertake something.",
  "Undeserved misfortune. The cow that was tethered by someone is the wanderer's gain, the citizen's loss.",
  "He who can be persevering remains without blame.",
  "Use no medicine in an illness incurred through no fault of your own. It will pass of itself.",
  "Innocent action brings misfortune. Nothing furthers."]),

(26, "100111", "大畜", "dà chù", "The Taming Power of the Great", "100", "111",
 "The Taming Power of the Great. Perseverance furthers. Not eating at home brings good fortune. It furthers one to cross the great water.",
 "大畜：利貞，不家食吉，利涉大川。",
 "Heaven within the mountain. Thus the superior man acquaints himself with many sayings of antiquity and many deeds of the past.",
 "天在山中，大畜；君子以多識前言往行，以畜其德。",
 ["Danger is at hand. It furthers one to desist.",
  "The axletrees are taken from the wagon.",
  "A good horse that follows others. Awareness of danger, with perseverance, furthers. Practice chariot driving and armed defense daily.",
  "The headboard of a young bull. Great good fortune.",
  "The tusk of a gelded boar. Good fortune.",
  "One attains the way of heaven. Success."]),

(27, "100001", "頤", "yí", "The Corners of the Mouth", "100", "001",
 "The Corners of the Mouth. Perseverance brings good fortune. Pay heed to the providing of nourishment and to what a man seeks to fill his own mouth with.",
 "頤：貞吉。觀頤，自求口實。",
 "At the foot of the mountain, thunder. Thus the superior man is careful of his words and temperate in eating and drinking.",
 "山下有雷，頤；君子以慎言語，節飲食。",
 ["You let your magic tortoise go, and look at me with the corners of your mouth drooping. Misfortune.",
  "Turning to the summit for nourishment. Deviating from the path to seek nourishment from the hill. Continuing to do this brings misfortune.",
  "Turning away from nourishment. Perseverance brings misfortune. Do not act thus for ten years. Nothing serves to further.",
  "Turning to the summit for provision of nourishment brings good fortune. Spying about with sharp eyes like a tiger with insatiable craving. No blame.",
  "Turning away from the path. To remain persevering brings good fortune. One should not cross the great water.",
  "The source of nourishment. Awareness of danger brings good fortune. It furthers one to cross the great water."]),

(28, "011110", "大過", "dà guò", "Preponderance of the Great", "011", "110",
 "Preponderance of the Great. The ridgepole sags to the breaking point. It furthers one to have somewhere to go. Success.",
 "大過：棟橈。利有攸往，亨。",
 "The lake rises above the trees. Thus the superior man, when he stands alone, is unconcerned, and if he has to renounce the world, he is undaunted.",
 "澤滅木，大過；君子以獨立不懼，遁世無悶。",
 ["To spread white rushes underneath. No blame.",
  "A dry poplar sprouts at the root. An older man takes a young wife. Everything furthers.",
  "The ridgepole sags to the breaking point. Misfortune.",
  "The ridgepole is braced. Good fortune. If there are ulterior motives, it is humiliating.",
  "A withered poplar puts forth flowers. An older woman takes a young husband. No blame. No praise.",
  "One must go through the water. It goes over one's head. Misfortune. No blame."]),

(29, "010010", "坎", "kǎn", "The Abysmal", "010", "010",
 "The Abysmal repeated. If you are sincere, you have success in your heart, and whatever you do succeeds.",
 "坎：習坎，有孚，維心亨，行有尚。",
 "Water flows on and reaches the goal. Thus the superior man walks in lasting virtue and carries on the business of teaching.",
 "水洊至，習坎；君子以常德行，習教事。",
 ["Repetition of the Abysmal. In the abyss one falls into a pit. Misfortune.",
  "The abyss is dangerous. One should strive to attain small things only.",
  "Forward and backward, abyss on abyss. In danger like this, pause at first and wait. Otherwise you will fall into a pit in the abyss. Do not act in this way.",
  "A jug of wine, a bowl of rice with it; earthen vessels simply handed in through the window. There is certainly no blame in this.",
  "The abyss is not filled to overflowing, it is filled only to the rim. No blame.",
  "Bound with cords and ropes, shut in between thorn-hedged prison walls. For three years one does not find the way. Misfortune."]),

(30, "101101", "離", "lí", "The Clinging", "101", "101",
 "The Clinging. Perseverance furthers. It brings success. Care of the cow brings good fortune.",
 "離：利貞，亨。畜牝牛，吉。",
 "That which is bright rises twice: The Clinging. Thus the great man, by perpetuating this brightness, illumines the four quarters of the world.",
 "明兩作，離；大人以繼明照于四方。",
 ["The footprints run crisscross. If one is seriously intent, no blame.",
  "Yellow light. Supreme good fortune.",
  "In the light of the setting sun, men either beat the pot and sing or loudly bewail the approach of old age. Misfortune.",
  "Its coming is sudden; it flames up, dies down, is thrown away.",
  "Tears in floods, sighing and lamenting. Good fortune.",
  "The king uses him to march forth and chastise. It is best to kill the leaders and take captive the followers. No blame."]),

(31, "011100", "咸", "xián", "Influence", "011", "100",
 "Influence. Success. Perseverance furthers. To take a maiden to wife brings good fortune.",
 "咸：亨，利貞，取女吉。",
 "A lake on the mountain. Thus the superior man encourages people to approach him by his readiness to receive them.",
 "山上有澤，咸；君子以虛受人。",
 ["The influence shows itself in the big toe.",
  "The influence shows itself in the calves of the legs. Misfortune. Tarrying brings good fortune.",
  "The influence shows itself in the thighs. Holds to that which follows it. To continue is humiliating.",
  "Perseverance brings good fortune. Remorse disappears. If a man is agitated in mind and his thoughts go hither and thither, only those friends on whom he fixes his conscious thoughts will follow.",
  "The influence shows itself in the back of the neck. No remorse.",
  "The influence shows itself in the jaws, cheeks, and tongue."]),

(32, "001110", "恆", "héng", "Duration", "001", "110",
 "Duration. Success. No blame. Perseverance furthers. It furthers one to have somewhere to go.",
 "恆：亨，無咎，利貞，利有攸往。",
 "Thunder and wind: Duration. Thus the superior man stands firm and does not change his direction.",
 "雷風，恆；君子以立不易方。",
 ["Seeking duration too hastily brings misfortune persistently. Nothing that would further.",
  "Remorse disappears.",
  "He who does not give duration to his character meets with disgrace. Persistent humiliation.",
  "No game in the field.",
  "Giving duration to one's character through perseverance. This is good fortune for a woman, misfortune for a man.",
  "Restlessness as an enduring condition brings misfortune."]),

(33, "111100", "遯", "dùn", "Retreat", "111", "100",
 "Retreat. Success. In what is small, perseverance furthers.",
 "遯：亨，小利貞。",
 "Mountain under heaven. Thus the superior man keeps the inferior man at a distance, not angrily but with reserve.",
 "天下有山，遯；君子以遠小人，不惡而嚴。",
 ["At the tail in retreat. This is dangerous. One must not wish to undertake anything.",
  "He holds him fast with yellow oxhide. No one can tear him loose.",
  "A halted retreat is nerve-wracking and dangerous. To retain people as men- and maidservants brings good fortune.",
  "Voluntary retreat brings good fortune to the superior man and downfall to the inferior man.",
  "Friendly retreat. Perseverance brings good fortune.",
  "Cheerful retreat. Everything serves to further."]),

(34, "001111", "大壯", "dà zhuàng", "The Power of the Great", "001", "111",
 "The Power of the Great. Perseverance furthers.",
 "大壯：利貞。",
 "Thunder in heaven above. Thus the superior man does not tread upon paths that do not accord with established order.",
 "雷在天上，大壯；君子以非禮弗履。",
 ["Power in the toes. Continuing brings misfortune. This is certainly true.",
  "Perseverance brings good fortune.",
  "The inferior man works through power. The superior man does not act thus. To continue is dangerous. A goat butts against a hedge and gets its horns entangled.",
  "Perseverance brings good fortune. Remorse disappears. The hedge opens; there is no entanglement. Power depends upon the axle of a big cart.",
  "Loses the goat with ease. No remorse.",
  "A goat butts against a hedge. It cannot go backward, it cannot go forward. Nothing serves to further. If one notes the difficulty, this brings good fortune."]),

(35, "101000", "晉", "jìn", "Progress", "101", "000",
 "Progress. The powerful prince is honored with horses in large numbers. In a single day he is granted audience three times.",
 "晉：康侯用錫馬蕃庶，晝日三接。",
 "The sun rises over the earth. Thus the superior man himself brightens his bright virtue.",
 "明出地上，晉；君子以自昭明德。",
 ["Progressing, but turned back. Perseverance brings good fortune. If one meets with no confidence, one should remain calm. No mistake.",
  "Progressing, but in sorrow. Perseverance brings good fortune. Then one obtains great happiness from one's ancestress.",
  "All are in accord. Remorse disappears.",
  "Progress like a hamster. Perseverance brings danger.",
  "Remorse disappears. Take not gain and loss to heart. Undertakings bring good fortune. Everything serves to further.",
  "Making progress with the horns is permissible only for the purpose of punishing one's own city. To be conscious of danger brings good fortune. No blame. Perseverance brings humiliation."]),

(36, "000101", "明夷", "míng yí", "Darkening of the Light", "000", "101",
 "Darkening of the Light. In adversity it furthers one to be persevering.",
 "明夷：利艱貞。",
 "The light has sunk into the earth. Thus does the superior man live with the great mass: he veils his light, yet still shines.",
 "明入地中，明夷；君子以蒞眾，用晦而明。",
 ["Darkening of the light during flight. He lowers his wings. The superior man does not eat for three days on his wanderings. But he has somewhere to go. The host has occasion to gossip.",
  "Darkening of the light injures him in the left thigh. He gives aid with the strength of a horse. Good fortune.",
  "Darkening of the light during the hunt in the south. Their great leader is captured. One must not expect perseverance too soon.",
  "He penetrates the left side of the belly. One gets at the very heart of the darkening of the light, and leaves gate and courtyard.",
  "Darkening of the light as with Prince Chi. Perseverance furthers.",
  "Not light but darkness. First he climbed up to heaven, then he plunged into the depths of the earth."]),

(37, "110101", "家人", "jiā rén", "The Family", "110", "101",
 "The Family. The perseverance of the woman furthers.",
 "家人：利女貞。",
 "Wind comes forth from fire. Thus the superior man has substance in his words and duration in his way of life.",
 "風自火出，家人；君子以言有物而行有恆。",
 ["Firm seclusion within the family. Remorse disappears.",
  "She should not follow her whims. She must attend within to the food. Perseverance brings good fortune.",
  "When tempers flare up in the family, too great severity brings remorse. Good fortune nonetheless. When woman and child dally and laugh, it leads in the end to humiliation.",
  "She is the treasure of the house. Great good fortune.",
  "As a king he approaches his family. Fear not. Good fortune.",
  "His work commands respect. In the end good fortune comes."]),

(38, "101011", "睽", "kuí", "Opposition", "101", "011",
 "Opposition. In small matters, good fortune.",
 "睽：小事吉。",
 "Above, fire; below, the lake. Thus amid all fellowship the superior man retains his individuality.",
 "上火下澤，睽；君子以同而異。",
 ["Remorse disappears. If you lose your horse, do not run after it; it will come back of its own accord.",
  "One meets his lord in a narrow street. No blame.",
  "One sees the wagon dragged back, the oxen halted, a man's hair and nose cut off. Not a good beginning, but a good end.",
  "Isolated through opposition, one meets a like-minded man with whom one can associate in good faith. Despite the danger, no blame.",
  "Remorse disappears. The companion bites his way through the wrappings. If one goes to him, how could it be a mistake?",
  "Isolated through opposition. One sees one's companion as a pig covered with dirt, as a wagon full of devils. First one draws a bow against him, then one lays the bow aside. He is not a robber; he will woo at the right time."]),

(39, "010100", "蹇", "jiǎn", "Obstruction", "010", "100",
 "Obstruction. The southwest furthers. The northeast does not further. It furthers one to see the great man. Perseverance brings good fortune.",
 "蹇：利西南，不利東北。利見大人，貞吉。",
 "Water on the mountain. Thus the superior man turns his attention to himself and molds his character.",
 "山上有水，蹇；君子以反身修德。",
 ["Going leads to obstructions, coming meets with praise.",
  "The king's servant is beset by obstruction upon obstruction, but it is not his own fault.",
  "Going leads to obstructions; hence he comes back.",
  "Going leads to obstructions, coming leads to union.",
  "In the midst of the greatest obstructions, friends come.",
  "Going leads to obstructions, coming leads to great good fortune. It furthers one to see the great man."]),

(40, "001010", "解", "xiè", "Deliverance", "001", "010",
 "Deliverance. The southwest furthers. If there is no longer anything where one has to go, return brings good fortune. If there is still something where one has to go, hastening brings good fortune.",
 "解：利西南，無所往，其來復吉。有攸往，夙吉。",
 "Thunder and rain set in. Thus the superior man pardons mistakes and forgives misdeeds.",
 "雷雨作，解；君子以赦過宥罪。",
 ["Without blame.",
  "One kills three foxes in the field and receives a yellow arrow. Perseverance brings good fortune.",
  "If a man carries a burden on his back and nonetheless rides in a carriage, he thereby encourages robbers to draw near. Perseverance leads to humiliation.",
  "Deliver yourself from your great toe. Then the companion comes, and him you can trust.",
  "If only the superior man can deliver himself, it brings good fortune. Thus he proves to inferior men that he is in earnest.",
  "The prince shoots at a hawk on a high wall. He kills it. Everything serves to further."]),

(41, "100011", "損", "sǔn", "Decrease", "100", "011",
 "Decrease combined with sincerity brings about supreme good fortune without blame. One may be persevering in this. It furthers one to undertake something. How is this to be carried out? One may use two small bowls for the sacrifice.",
 "損：有孚，元吉，無咎，可貞，利有攸往。曷之用？二簋可用享。",
 "At the foot of the mountain, the lake. Thus the superior man controls his anger and restrains his instincts.",
 "山下有澤，損；君子以懲忿窒慾。",
 ["Going quickly when one's tasks are finished is without blame. But one must reflect on how much one may decrease others.",
  "Perseverance furthers. To undertake something brings misfortune. Without decreasing oneself, one is able to bring increase to others.",
  "When three people journey together, their number decreases by one. When one man journeys alone, he finds a companion.",
  "If a man decreases his faults, it makes the other hasten to come and rejoice. No blame.",
  "Someone does indeed increase him. Ten pairs of tortoises cannot oppose it. Supreme good fortune.",
  "If one is increased without depriving others, there is no blame. Perseverance brings good fortune. It furthers one to undertake something."]),

(42, "110001", "益", "yì", "Increase", "110", "001",
 "Increase. It furthers one to undertake something. It furthers one to cross the great water.",
 "益：利有攸往，利涉大川。",
 "Wind and thunder: Increase. Thus the superior man: If he sees good, he imitates it; if he has faults, he rids himself of them.",
 "風雷，益；君子以見善則遷，有過則改。",
 ["It furthers one to accomplish great deeds. Supreme good fortune. No blame.",
  "Someone does indeed increase him; ten pairs of tortoises cannot oppose it. Constant perseverance brings good fortune. The king presents him before God. Good fortune.",
  "One is enriched through unfortunate events. No blame, if you are sincere and walk in the middle, and report with a seal to the prince.",
  "If you walk in the middle and report to the prince, he will follow. It furthers one to be used in the removal of the capital.",
  "If in truth you have a kind heart, ask not. Supreme good fortune. Truly, kindness will be recognized as your virtue.",
  "He brings increase to no one. Indeed, someone even strikes him. He does not keep his heart constantly steady. Misfortune."]),

(43, "011111", "夬", "guài", "Breakthrough", "011", "111",
 "Breakthrough. One must resolutely make the matter known at the court of the king. It must be announced truthfully. Danger. It is necessary to notify one's own city. It does not further to resort to arms. It furthers one to undertake something.",
 "夬：揚于王庭，孚號，有厲，告自邑，不利即戎，利有攸往。",
 "The lake has risen up to heaven. Thus the superior man dispenses riches downward and refrains from resting on his virtue.",
 "澤上於天，夬；君子以施祿及下，居德則忌。",
 ["Mighty in the forward-striding toes. When one goes and is not equal to the task, one makes a mistake.",
  "A cry of alarm. Arms at evening and at night. Fear nothing.",
  "To be powerful in the cheekbones brings misfortune. The superior man is firmly resolved. He walks alone and is caught in the rain. He is bespattered, and people murmur against him. No blame.",
  "There is no skin on his thighs, and walking comes hard. If a man were to let himself be led like a sheep, remorse would disappear. But if these words are heard, they will not be believed.",
  "In dealing with weeds, firm resolution is necessary. Walking in the middle remains free of blame.",
  "No cry. In the end misfortune comes."]),

(44, "111110", "姤", "gòu", "Coming to Meet", "111", "110",
 "Coming to Meet. The maiden is powerful. One should not marry such a maiden.",
 "姤：女壯，勿用取女。",
 "Under heaven, wind. Thus does the prince act when disseminating his commands and proclaiming them to the four quarters of heaven.",
 "天下有風，姤；后以施命誥四方。",
 ["It must be checked with a brake of bronze. Perseverance brings good fortune. If one lets it take its course, one experiences misfortune.",
  "There is a fish in the tank. No blame. Does not further guests.",
  "There is no skin on his thighs, and walking comes hard. If one is mindful of the danger, no great mistake is made.",
  "No fish in the tank. This leads to misfortune.",
  "A melon covered with willow leaves. Hidden lines. Then it drops down to one from heaven.",
  "He comes to meet with his horns. Humiliation. No blame."]),

(45, "011000", "萃", "cuì", "Gathering Together", "011", "000",
 "Gathering Together. Success. The king approaches his temple. It furthers one to see the great man. This brings success. Perseverance furthers. To bring great offerings creates good fortune. It furthers one to undertake something.",
 "萃：亨。王假有廟，利見大人，亨，利貞。用大牲吉，利有攸往。",
 "Over the earth, the lake. Thus the superior man renews his weapons in order to meet the unforeseen.",
 "澤上於地，萃；君子以除戎器，戒不虞。",
 ["If you are sincere, but not to the end, there will sometimes be confusion, sometimes gathering together. If you call out, then after one grasp of the hand you can laugh again. Regret not. Going is without blame.",
  "Letting oneself be drawn brings good fortune and remains blameless. If one is sincere, it furthers one to bring even a small offering.",
  "Gathering together amid sighs. Nothing that would further. Going is without blame. Slight humiliation.",
  "Great good fortune. No blame.",
  "If in gathering together one has position, this brings no blame. If there are some who are not yet sincerely in the work, sublime and enduring perseverance is needed. Then remorse disappears.",
  "Lamenting and sighing, floods of tears. No blame."]),

(46, "000110", "升", "shēng", "Pushing Upward", "000", "110",
 "Pushing Upward has supreme success. One must see the great man. Fear not. Departure toward the south brings good fortune.",
 "升：元亨，用見大人，勿恤，南征吉。",
 "Within the earth, wood grows. Thus the superior man of devoted character heaps up small things in order to achieve something high and great.",
 "地中生木，升；君子以順德，積小以高大。",
 ["Pushing upward that meets with confidence brings great good fortune.",
  "If one is sincere, it furthers one to bring even a small offering. No blame.",
  "One pushes upward into an empty city.",
  "The king offers him Mount Ch'i. Good fortune. No blame.",
  "Perseverance brings good fortune. One pushes upward by steps.",
  "Pushing upward in darkness. It furthers one to be unremittingly persevering."]),

(47, "011010", "困", "kùn", "Oppression", "011", "010",
 "Oppression. Success. Perseverance. The great man brings about good fortune. No blame. When one has something to say, it is not believed.",
 "困：亨，貞，大人吉，無咎，有言不信。",
 "There is no water in the lake. Thus the superior man stakes his life on following his will.",
 "澤無水，困；君子以致命遂志。",
 ["One sits oppressed under a bare tree and strays into a gloomy valley. For three years one sees nothing.",
  "One is oppressed while at meat and drink. The man with the scarlet knee bands is just coming. It furthers one to offer sacrifice. To set forth brings misfortune. No blame.",
  "One is oppressed by stone, and leans on thorns and thistles. He enters the house and does not see his wife. Misfortune.",
  "He comes very quietly, oppressed in a golden carriage. Humiliation, but the end is reached.",
  "His nose and feet are cut off. Oppression at the hands of the man with the purple knee bands. Joy comes softly. It furthers one to make offerings and libations.",
  "He is oppressed by creeping vines. He says to himself: Movement brings remorse. If one feels remorse over this and makes a start, good fortune comes."]),

(48, "010110", "井", "jǐng", "The Well", "010", "110",
 "The Well. The town may be changed, but the well cannot be changed. It neither decreases nor increases. They come and go and draw from the well.",
 "井：改邑不改井，無喪無得，往來井井。",
 "Water over wood: The Well. Thus the superior man encourages the people at their work, and exhorts them to help one another.",
 "木上有水，井；君子以勞民勸相。",
 ["One does not drink the mud of the well. No animals come to an old well.",
  "At the wellhole one shoots fishes. The jug is broken and leaks.",
  "The well is cleaned, but no one drinks from it. This is my heart's sorrow, for one might draw from it. If the king were clear-minded, good fortune might be enjoyed in common.",
  "The well is being lined. No blame.",
  "In the well there is a clear, cold spring from which one can drink.",
  "One draws from the well without hindrance. It is dependable. Supreme good fortune."]),

(49, "011101", "革", "gé", "Revolution", "011", "101",
 "Revolution. On your own day you are believed. Supreme success, furthering through perseverance. Remorse disappears.",
 "革：己日乃孚，元亨利貞，悔亡。",
 "Fire in the lake: Revolution. Thus the superior man sets the calendar in order and makes the seasons clear.",
 "澤中有火，革；君子以治曆明時。",
 ["Wrapped in the hide of a yellow cow.",
  "When one's own day comes, one may create revolution. Starting brings good fortune. No blame.",
  "Starting brings misfortune. Perseverance brings danger. When talk of revolution has gone the rounds three times, one may commit himself, and men will believe him.",
  "Remorse disappears. Men believe him. Changing the form of government brings good fortune.",
  "The great man changes like a tiger. Even before questioning the oracle he is believed.",
  "The superior man changes like a panther. The inferior man molts in the face. Starting brings misfortune. To remain persevering brings good fortune."]),

(50, "101110", "鼎", "dǐng", "The Caldron", "101", "110",
 "The Caldron. Supreme good fortune. Success.",
 "鼎：元吉，亨。",
 "Fire over wood: The Caldron. Thus the superior man consolidates his fate by making his position correct.",
 "木上有火，鼎；君子以正位凝命。",
 ["A ting with legs upturned. It furthers to remove stagnating stuff. One takes a concubine for the sake of her son. No blame.",
  "There is food in the ting. My comrades are envious, but they cannot harm me. Good fortune.",
  "The handle of the ting is altered. One is impeded in his way of life. The fat of the pheasant is not eaten. Once rain falls, remorse is spent. Good fortune comes in the end.",
  "The legs of the ting are broken. The prince's meal is spilled and his person is soiled. Misfortune.",
  "The ting has yellow handles, golden carrying rings. Perseverance furthers.",
  "The ting has rings of jade. Great good fortune. Nothing that would not act to further."]),

(51, "001001", "震", "zhèn", "The Arousing", "001", "001",
 "Shock brings success. Shock comes — Loss, loss! But things are not lost. After the shock comes renewed order.",
 "震：亨。震來虩虩，笑言啞啞。震驚百里，不喪匕鬯。",
 "Thunder repeated: The Arousing. Thus in fear and trembling the superior man sets his life in order and examines himself.",
 "洊雷，震；君子以恐懼修省。",
 ["Shock comes — Loss, loss! Then follow laughing words — Ha, ha! Good fortune.",
  "Shock comes bringing danger. A hundred thousand times you lose your treasures and climb the nine hills. Do not go in pursuit of them. After seven days you will get them back again.",
  "Shock comes and makes one distraught. If shock spurs to action, one remains free of misfortune.",
  "Shock is mired.",
  "Shock goes hither and thither. Danger. However, nothing at all is lost. Yet there are things to be done.",
  "Shock brings ruin and terrified gazing around. Going ahead brings misfortune. If it has not yet touched one's own body but has reached one's neighbor first, there is no blame."]),

(52, "100100", "艮", "gèn", "Keeping Still", "100", "100",
 "Keeping Still. Keeping his back so still that he no longer feels his body. He goes into his courtyard and does not see his people. No blame.",
 "艮：艮其背，不獲其身，行其庭不見其人，無咎。",
 "Mountains standing close together: Keeping Still. Thus the superior man does not permit his thoughts to go beyond his situation.",
 "兼山，艮；君子以思不出其位。",
 ["Keeping his toes still. No blame. Continued perseverance furthers.",
  "Keeping his calves still. He cannot rescue him whom he follows. His heart is not glad.",
  "Keeping his hips still. Making his sacrum stiff. Dangerous. The heart suffocates.",
  "Keeping his trunk still. No blame.",
  "Keeping his jaws still. The words have order. Remorse disappears.",
  "Noble-hearted keeping still. Good fortune."]),

(53, "110100", "漸", "jiàn", "Development", "110", "100",
 "Development. The maiden is given in marriage. Good fortune. Perseverance furthers.",
 "漸：女歸吉，利貞。",
 "On the mountain, a tree. Thus the superior man abides in dignity and virtue, in order to improve the mores.",
 "山上有木，漸；君子以居賢德善俗。",
 ["The wild goose gradually draws near the shore. The young son is in danger. There is talk. No blame.",
  "The wild goose gradually draws near the cliff. Eating and drinking in peace and concord. Good fortune.",
  "The wild goose gradually draws near the plateau. The man goes forth and does not return. The woman carries a child but does not bring it forth. Misfortune.",
  "The wild goose gradually draws near the tree. Perhaps it will find a flat branch. No blame.",
  "The wild goose gradually draws near the summit. For three years the woman has no child. In the end nothing can hinder her. Good fortune.",
  "The wild goose gradually draws near the cloud heights. Its feathers can be used for the sacred dance. Good fortune."]),

(54, "001011", "歸妹", "guī mèi", "The Marrying Maiden", "001", "011",
 "The Marrying Maiden. Undertakings bring misfortune. Nothing that would further.",
 "歸妹：征凶，無攸利。",
 "Thunder over the lake: The Marrying Maiden. Thus the superior man understands the transitory in the light of the eternity of the end.",
 "澤上有雷，歸妹；君子以永終知敝。",
 ["The marrying maiden as a concubine. A lame man who is able to tread. Undertakings bring good fortune.",
  "A one-eyed man who is able to see. The perseverance of a solitary man furthers.",
  "The marrying maiden as a slave. She marries as a concubine.",
  "The marrying maiden draws out the allotted time. A late marriage comes in due course.",
  "The sovereign I gave his daughter in marriage. The embroidered garments of the princess were not as gorgeous as those of the servingmaid. The moon that is nearly full brings good fortune.",
  "The woman holds the basket, but there are no fruits in it. The man stabs the sheep, but no blood flows. Nothing that acts to further."]),

(55, "001101", "豐", "fēng", "Abundance", "001", "101",
 "Abundance has success. The king attains abundance. Be not sad. Be like the sun at midday.",
 "豐：亨，王假之，勿憂，宜日中。",
 "Both thunder and lightning come: Abundance. Thus the superior man decides lawsuits and carries out punishments.",
 "雷電皆至，豐；君子以折獄致刑。",
 ["When a man meets his destined ruler, they can be together ten days, and it is not a mistake. Going meets with recognition.",
  "The curtain is of such fullness that the polestars can be seen at noon. Through going one meets with mistrust and hate. If one rouses him through truth, good fortune comes.",
  "The underbrush is of such abundance that the small stars can be seen at noon. He breaks his right arm. No blame.",
  "The curtain is of such fullness that the polestars can be seen at noon. He meets his ruler, who is of like kind. Good fortune.",
  "Lines are coming. Blessing and fame draw near. Good fortune.",
  "His house is in a state of abundance. He screens off his family. He peers through the gate and no longer perceives anyone. For three years he sees nothing. Misfortune."]),

(56, "101100", "旅", "lǚ", "The Wanderer", "101", "100",
 "The Wanderer. Success through smallness. Perseverance brings good fortune to the wanderer.",
 "旅：小亨，旅貞吉。",
 "Fire on the mountain: The Wanderer. Thus the superior man is clear-minded and cautious in imposing penalties, and protracts no lawsuits.",
 "山上有火，旅；君子以明慎用刑而不留獄。",
 ["If the wanderer busies himself with trivial things, he draws down misfortune upon himself.",
  "The wanderer comes to an inn. He has his property with him. He wins the steadfastness of a young servant.",
  "The wanderer's inn burns down. He loses the steadfastness of his young servant. Danger.",
  "The wanderer rests in a shelter. He obtains his property and an axe. My heart is not glad.",
  "He shoots a pheasant. It drops with the first arrow. In the end this brings both praise and office.",
  "The bird's nest burns up. The wanderer laughs first, then must needs lament and weep. Through carelessness he loses his cow. Misfortune."]),

(57, "110110", "巽", "xùn", "The Gentle", "110", "110",
 "The Gentle. Success through what is small. It furthers one to have somewhere to go. It furthers one to see the great man.",
 "巽：小亨，利有攸往，利見大人。",
 "Winds following one upon the other: The Gentle. Thus the superior man spreads his commands abroad and carries out his undertakings.",
 "隨風，巽；君子以申命行事。",
 ["In advancing and in retreating, the perseverance of a warrior furthers.",
  "Penetration under the bed. Priests and magicians are used in great number. Good fortune. No blame.",
  "Repeated penetration. Humiliation.",
  "Remorse vanishes. During the hunt three kinds of game are caught.",
  "Perseverance brings good fortune. Remorse vanishes. Nothing that does not further. No beginning, but an end. Before the change, three days. After the change, three days. Good fortune.",
  "Penetration under the bed. He loses his property and his axe. Perseverance brings misfortune."]),

(58, "011011", "兌", "duì", "The Joyous", "011", "011",
 "The Joyous. Success. Perseverance is favorable.",
 "兌：亨，利貞。",
 "Lakes resting one on the other: The Joyous. Thus the superior man joins with his friends for discussion and practice.",
 "麗澤，兌；君子以朋友講習。",
 ["Contented joyousness. Good fortune.",
  "Sincere joyousness. Good fortune. Remorse disappears.",
  "Coming joyousness. Misfortune.",
  "Joyousness that is weighed is not at peace. After ridding himself of mistakes a man has joy.",
  "Sincerity toward disintegrating influences is dangerous.",
  "Seductive joyousness."]),

(59, "110010", "渙", "huàn", "Dispersion", "110", "010",
 "Dispersion. Success. The king approaches his temple. It furthers one to cross the great water. Perseverance furthers.",
 "渙：亨。王假有廟，利涉大川，利貞。",
 "The wind drives over the water: Dispersion. Thus the kings of old sacrificed to the Lord and built temples.",
 "風行水上，渙；先王以享于帝立廟。",
 ["He brings help with the strength of a horse. Good fortune.",
  "At the dissolution he hurries to that which supports him. Remorse disappears.",
  "He dissolves his self. No remorse.",
  "He dissolves his bond with his group. Supreme good fortune. Dispersion leads in turn to accumulation. This is something that ordinary men do not think of.",
  "His loud cries are as dissolving as sweat. Dissolution. A king abides without blame.",
  "He dissolves his blood. Departing, keeping at a distance, going out, is without blame."]),

(60, "010011", "節", "jié", "Limitation", "010", "011",
 "Limitation. Success. Galling limitation must not be persevered in.",
 "節：亨。苦節不可貞。",
 "Water over lake: Limitation. Thus the superior man creates number and measure, and examines the nature of virtue and correct conduct.",
 "澤上有水，節；君子以制數度，議德行。",
 ["Not going out of the door and the courtyard is without blame.",
  "Not going out of the gate and the courtyard brings misfortune.",
  "He who knows no limitation will have cause to lament. No blame.",
  "Contented limitation. Success.",
  "Sweet limitation brings good fortune. Going brings esteem.",
  "Galling limitation. Perseverance brings misfortune. Remorse disappears."]),

(61, "110011", "中孚", "zhōng fú", "Inner Truth", "110", "011",
 "Inner Truth. Pigs and fishes. Good fortune. It furthers one to cross the great water. Perseverance furthers.",
 "中孚：豚魚吉，利涉大川，利貞。",
 "Wind over lake: Inner Truth. Thus the superior man discusses criminal cases in order to delay executions.",
 "澤上有風，中孚；君子以議獄緩死。",
 ["Being prepared brings good fortune. If there are secret designs, it is disquieting.",
  "A crane calling in the shade. Its young answers it. I have a good goblet. I will share it with you.",
  "He finds a comrade. Now he beats the drum, now he stops. Now he sobs, now he sings.",
  "The moon nearly at the full. The team horse goes astray. No blame.",
  "He possesses truth, which links together. No blame.",
  "Cockcrow penetrating to heaven. Perseverance brings misfortune."]),

(62, "001100", "小過", "xiǎo guò", "Preponderance of the Small", "001", "100",
 "Preponderance of the Small. Success. Perseverance furthers. Small things may be done; great things should not be done. The flying bird brings the message: It is not well to strive upward, it is well to remain below. Great good fortune.",
 "小過：亨，利貞，可小事，不可大事。飛鳥遺之音，不宜上宜下，大吉。",
 "Thunder on the mountain: Preponderance of the Small. Thus in his conduct the superior man gives preponderance to reverence. In bereavement he gives preponderance to grief. In his expenditures he gives preponderance to thrift.",
 "山上有雷，小過；君子以行過乎恭，喪過乎哀，用過乎儉。",
 ["The bird meets with misfortune through flying.",
  "She passes by her ancestor and meets her ancestress. He does not reach his prince and meets the official. No blame.",
  "If one is not extremely careful, somebody may come up from behind and strike him. Misfortune.",
  "No blame. He meets him without passing by. Going brings danger. One must be on guard. Do not act. Be constantly persevering.",
  "Dense clouds, no rain from our western territory. The prince shoots and hits him who is in the cave.",
  "He passes him by, not meeting him. The flying bird leaves him. Misfortune. This means bad luck and injury."]),

(63, "010101", "既濟", "jì jì", "After Completion", "010", "101",
 "After Completion. Success in small matters. Perseverance furthers. At the beginning good fortune, at the end disorder.",
 "既濟：亨，小利貞，初吉終亂。",
 "Water over fire: After Completion. Thus the superior man takes thought of misfortune and arms himself against it in advance.",
 "水在火上，既濟；君子以思患而豫防之。",
 ["He brakes his wheels. He gets his tail in the water. No blame.",
  "The woman loses the curtain of her carriage. Do not run after it; on the seventh day you will get it.",
  "The Illustrious Ancestor disciplines the Devil's Country. After three years he conquers it. Inferior people must not be employed.",
  "The finest clothes turn to rags. Be careful all day long.",
  "The neighbor in the east who slaughters an ox does not attain as much real happiness as the neighbor in the west with his small offering.",
  "He gets his head in the water. Danger."]),

(64, "101010", "未濟", "wèi jì", "Before Completion", "101", "010",
 "Before Completion. Success. But if the little fox, after nearly completing the crossing, gets his tail in the water, there is nothing that would further.",
 "未濟：亨，小狐汔濟，濡其尾，無攸利。",
 "Fire over water: Before Completion. Thus the superior man is careful in the differentiation of things, so that each finds its place.",
 "火在水上，未濟；君子以慎辨物居方。",
 ["He gets his tail in the water. Humiliating.",
  "He brakes his wheels. Perseverance brings good fortune.",
  "Before completion, attack brings misfortune. It furthers one to cross the great water.",
  "Perseverance brings good fortune. Remorse disappears. Shock, thus to discipline the Devil's Country. For three years, great realms are awarded.",
  "Perseverance brings good fortune. No remorse. The light of the superior man is true. Good fortune.",
  "Drinking wine in genuine confidence. No blame. But if one wets his head, he loses it, in truth."])
]

def build_hexagram(data):
    num, binary, ch, py, en, upper, lower, j_en, j_cn, i_en, i_cn, lines = data
    return {
        "number": num,
        "binary": binary,
        "name": {"chinese": ch, "pinyin": py, "english": en},
        "trigrams": {"upper": upper, "lower": lower},
        "judgment": {"text": j_en, "chinese": j_cn},
        "image": {"text": i_en, "chinese": i_cn},
        "lines": [{"position": i+1, "text": lines[i]} for i in range(6)]
    }

result = {"hexagrams": [build_hexagram(h) for h in HEXAGRAMS]}

with open("data/hexagrams.json", "w", encoding="utf-8") as f:
    json.dump(result, f, ensure_ascii=False, indent=2)

print(f"Generated {len(result['hexagrams'])} hexagrams")
